#ifndef TEX_TYPE_H
#define TEX_TYPE_H

typedef enum
{
    TEX_NONE,
    TEX_FACE,
    TEX_BLOCK,
    TEX_BLOCK_SOLID,
    TEX_BACKGROUND,
    TEX_PADDLE,
    TEX_PARTICLE,
    TEX_POWUP_SPEED,
    TEX_POWUP_STICKY,
    TEX_POWUP_PASS_THROUGH,
    TEX_POWUP_PAD_SIZE_INCREASE,
    TEX_POWUP_CONFUSE,
    TEX_POWUP_CHAOS,
    TEX_COUNT
} TexType;

#endif
